config/routes.rb
Footsteps::Application.routes.draw do

  get "users/index"
  get "welcome/index"
  devise_for :users

  resources :users, :only => [:index]

  get '/users/:id' => 'users#show', :as => :user
  match '/users/follow' => 'users#follow', :as => :follow, :via => [:post]
  match '/users/unfollow' => 'users#unfollow', :as => :unfollow, :via => [:post]

  root 'welcome#index'

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  belongs_to :from, :class_name => "User"
  belongs_to :to, :class_name => "User"

  validates :from, :presence => true
  validates :to, :presence => true
  
  validates :from, :uniqueness => { :scope => :to }, :allow_nil => true

  validate :cannot_follow_yourself

  def cannot_follow_yourself
    if from == to
      errors.add :to, 'You cannot follow yourself'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :uniqueness => { case_sensitive: false }, :presence => true

  has_many :follows_from, :foreign_key => "from_id", :class_name => "Follow"
  has_many :follows_to, :foreign_key => "to_id", :class_name => "Follow"
  has_many :followed, :through => :follows_from, :source => "to"
  has_many :followers, :through => :follows_to, :source => "from"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index
    @users = User.all
  end

  def show
    @user = User.find_by :id => params[:id]
    @follows = @user.followed
    @notfollows = User.all - (@follows) - [@user]
    @followers =  @user.followers
    if @user.nil?
      flash[:notice] = "That user does not exist!"
      redirect_to root_url
    end
  end


  # POST /follow
  def follow
    if user_signed_in?
      other_user = User.find_by :id => params[:id]
      Follow.create(:from => current_user, :to => other_user)
      flash[:notice] = "User '" + other_user[:name].to_s + "' followed."
      redirect_to :back
    else
      flash[:notice] = "You cannot follow someone when not logged in."
      redirect_to root_url
    end
  end

  # POST /unfollow
  def unfollow
    if user_signed_in?
      other_user = User.find_by :id => params[:id]
      @f = Follow.find_by(:from => current_user, :to => other_user)
      @f.destroy
      #Follow.destroy_all :from => current_user, :to => other_user
      flash[:notice] = "User '" + other_user[:name].to_s + "' unfollowed."
      redirect_to :back
    else
      flash[:notice] = "You cannot unfollow someone when not logged in."
      redirect_to root_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Footsteps</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <%= link_to "My profile", current_user %>
  <% else %>
  <%= link_to "Sign in", new_user_session_path %>   
  <%= link_to "Sign up", new_user_registration_path %>   
  <% end %>
  <%= link_to "User list", users_index_path %>   
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>List of Users</h1>
<ui>
<% @users.each do |user| %>
<li><%= user[:name] %> <%= link_to "Profile", user %></li>
<% end %>
</ui>

app/views/users/show.html.erb
<h1>Profile for <%= @user[:name] %></h1>

Hi there, my name is <%= @user[:name] %>.

<% if user_signed_in? and @user[:id] != current_user[:id] %>
<% if Follow.find_by(:from => current_user, :to => @user) %>
<%= link_to "unfollow", unfollow_path(:id => @user[:id]), :method => :post %>
<% else %>
<%= link_to "follow", follow_path(:id => @user[:id]), :method => :post %>
<% end %>
<% end %>

<Div id="following">
<h2>Following</h2>
<% if @follows.nil? %>
<p>You are not following anyone.</p>
<% else %>
<ul>
<% [*@follows].each do |user| %>
<li><%= user[:name] %> <%= link_to "Profile", user %>
  <% if user_signed_in? %>
  <%= link_to "Unfollow", unfollow_path(:id => user[:id]), :method => :post %>
  <% end %>
</li>
<% end %>
</ul>
<% end %>
</div>

<div id="not-following">
<h2>Not Following</h2>
<% if @notfollows.nil? %>
<p>You are following everyone.</p>
<% else %>
<ul>
<% [*@notfollows].each do |user| %>
<li><%= user[:name] %> <%= link_to "Profile", user %>
  <% if user_signed_in? %>
  <%= link_to "Follow", follow_path(:id => user[:id]), :method => :post %>
  <% end %>
</li>
<% end %>
</ul>
<% end %>
</div>

<div id="followers">
<h2>Followers</h2>
<% if @followers.nil? %>
<p>You have no followers.</p>
<% else %>
<ul>
<% [*@followers].each do |user| %>
<li><%= user[:name] %> <%= link_to "Profile", user %></li>
<% end %>
</ul>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>